### ISSUE TITLE
cannot run alpine image

### ISSUE THREAD

**Issue by thehajime** [ukontainer/dockerd-darwin#10]
while we can run thehajime/runu-base:0.1 image, I can't with alpine:latest while ctr can.

```
% docker -H tcp://127.0.0.1:3939 run --rm -e UMP_VERBOSE=1  --runtime=runu-dev --platform=linux/amd64 --net=none  alpine:latest uname -a
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
docker: operating system is not supported.
See 'docker run --help'.
```

**Comment by Aniketh01** [comment]
Is this the command you used to test alphine with ctr? `ctr --debug -a /tmp/ctrd/run/containerd/containerd.sock \
    run --fifo-dir /tmp/ctrd --env RUMP_VERBOSE=1 \
    --env RUNU_AUX_DIR=$RUNU_AUX_DIR --env LKL_USE_9PFS=1 \
    docker.io/library/alpine:latest alpine1 /bin/busybox ls -l`

**Comment by thehajime** [comment]
> Is this the command ?

yes

**Comment by Aniketh01** [comment]
I was looking at the cause of this bug. It wasn't able to pass the OS supported or not condition. So, I added a small line to fix it. Now it pulls/downloaded properly. 

This is the function call to register the image that has been downloaded with the layer store: https://github.com/ukontainer/dockerd-darwin/blob/darwin-port/distribution/xfer/download.go#L169

In this call, it seems rootFS.ChainID() is empty. I think we need to fill that?

**Comment by thehajime** [comment]
i'm not sure, but it sounds right.

but why runu-base:0.1 can be downloaded while we cannot alpine is still questionable.

**Comment by Aniketh01** [comment]
DEBU[2019-07-23T15:23:03.674859000+09:00] Calling POST /v1.41/images/create?fromImage=thehajime%2Frunu-base&tag=0.1

**Comment by Aniketh01** [comment]
DEBU[2019-07-23T15:23:03.674859000+09:00] Calling POST /v1.41/images/create?fromImage=thehajime%2Frunu-base&tag=0.1

**Comment by Aniketh01** [comment]
DEBU[2019-07-23T15:23:03.674859000+09:00] Calling POST /v1.41/images/create?fromImage=thehajime%2Frunu-base&tag=0.1

**Comment by Aniketh01** [comment]
This is a debug message while pulling our runu-base image: 
DEBU[2019-07-23T15:23:03.674859000+09:00] Calling POST /v1.41/images/create?fromImage=thehajime%2Frunu-base&tag=0.1

This is a debug message while pulling a alpine image:
DEBU[2019-07-23T15:20:22.261283000+09:00] Calling POST /v1.41/images/create?fromImage=alpine&platform=linux%2Famd64&tag=latest

Here while pulling the image for alpine it is specified to pull image alpine for linux platform, while there is no specific parameter passed in for the platform requirement in the POST request. 

Let me see how ctr does it with containerd and see if we can propose a fix for dockerd in similar.

**Comment by Aniketh01** [comment]
I was looking into this issue: Currently I am letting this check passed `IsOSSupported()`. But once that is the done, the image/layers are getting downloaded, but I end up with such an error:

DEBU[2019-07-23T16:56:40.202393000+09:00] Downloaded 050382585609 to tempfile /private/var/lib/docker/tmp/GetImageBlob465682208
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x101238fad]

goroutine 125 [running]:
github.com/docker/docker/distribution/xfer.(*LayerDownloadManager).makeDownloadFunc.func1.1(0xc0008de660, 0xc0008de540, 0x1023efe80, 0xc000c6e0b0, 0x0, 0xc00020bb00, 0xc000161d80, 0xc0008de600, 0xc000c739e0)
	/Users/aniketh/go/src/github.com/docker/docker/distribution/xfer/download.go:351 +0xffd
created by github.com/docker/docker/distribution/xfer.(*LayerDownloadManager).makeDownloadFunc.func1
	/Users/aniketh/go/src/github.com/docker/docker/distribution/xfer/download.go:233 +0x1ac

Is it because of the failure to read/write into this file /private/var/lib/docker/tmp/GetImageBlob465682208?

**Comment by Aniketh01** [comment]
The above error is since the ldm.layerStores[os] is empty: https://github.com/ukontainer/dockerd-darwin/blob/darwin-port/distribution/xfer/download.go#L230 and henceforth `d.layerStore` is nil.

In linux these are the items filled in `d.layerStore` while using `vfs` as the graphdriver: &{%!s(*layer.fileMetadataStore=&{/var/lib/docker/image/vfs/layerdb}) %!s(*graphdriver.NaiveDiffDriver=&{0xc0008351a0 [] []}) %!s(bool=true) map[] {%!s(int32=0) %!s(uint32=0)} map[] {%!s(int32=0) %!s(uint32=0)} %!s(*locker.Locker=&{{0 0} map[]}) linux}

**Comment by Aniketh01** [comment]
I suspect this to be originating from the graph driver, vfs as it is not able to deflate the image to bundle properly and fill in the layer store.

**Comment by thehajime** [comment]
I tentatively push a commit to work around this issue. let's go back again and reopen this issue once we found nicer/proper fix.
